services:
  postgres:
    image: postgres:17.4
    restart: always
    environment:
      - POSTGRES_USER=spire_stats
      - POSTGRES_PASSWORD=supersecret
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/run/postgresql/data
volumes:
  postgres:
